projects:
  chatapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        apiId: null
        maxDepth: 3
        region: ap-southeast-1
extensions:
  amplify:
    version: 3
